PACKAGE_NAME="xt-ts3init"
pushd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null
PACKAGE_VERSION=$(./version.sh)
popd >/dev/null

BUILT_MODULE_NAME[0]="xt_ts3init"
BUILT_MODULE_LOCATION[0]="src"
DEST_MODULE_LOCATION[0]="/extra"
STRIP[0]="no"
MAKE[0]="make -C src KVER=$kernelver modules"
CLEAN="make -C src KVER=$kernelver clean"
AUTOINSTALL="yes"
